export const meta = {
  name: 'masterclass-reverify29',
  description: 'Re-verifica cele 29 capitole Masterclass traduse dar neverificate (verify-only, pe slug)',
  phases: [{ title: 'Verify', detail: 'verifica traducerea + 25 intrebari fata de sursa EN, corecteaza in fisiere' }],
}
const DB='/Users/savulescucristian/stockmarketcap/stockmarketcap/data/stocks.db'; const SRC='/Users/savulescucristian/clubul-financiar/docs/masterclass/_src'; const QZ='/Users/savulescucristian/clubul-financiar/docs/masterclass/_quiz'
const SPECS=[{"slug": "regula-wash-sale-vanzare-fictiva-pierdere", "rid": 351, "domain": "compliance"}, {"slug": "legatura-credit-actiuni-marje-spread", "rid": 585, "domain": "credit"}, {"slug": "legatura-credit-actiuni-spread-uri-pret-bursa", "rid": 710, "domain": "credit"}, {"slug": "riscul-de-neplata-cum-se-masoara-probabilitatea-default", "rid": 592, "domain": "credit"}, {"slug": "riscul-de-neplata-probabilitatea-de-default-pd", "rid": 723, "domain": "credit"}, {"slug": "riscul-de-neplata-probabilitatea-de-neplata-pd", "rid": 818, "domain": "credit"}, {"slug": "risc-dificultate-financiara-stres-vs-default-semne-avertizar", "rid": 716, "domain": "credit"}, {"slug": "distress-risk-stres-financiar-vs-default-semne-avertizare", "rid": 730, "domain": "credit"}, {"slug": "risc-dificultate-financiara-semne-avertizare-timpurie", "rid": 823, "domain": "credit"}, {"slug": "obligatiuni-grad-investitie-vs-randament-ridicat", "rid": 606, "domain": "credit"}, {"slug": "obligatiuni-investment-grade-vs-high-yield", "rid": 736, "domain": "credit"}, {"slug": "obligatiuni-investment-grade-vs-high-yield-2", "rid": 837, "domain": "credit"}, {"slug": "participanti-piata-de-credit-investitori-emitenti-rating", "rid": 615, "domain": "credit"}, {"slug": "participanti-piata-de-credit", "rid": 739, "domain": "credit"}, {"slug": "participanti-piata-de-credit-2", "rid": 843, "domain": "credit"}, {"slug": "levier-financiar-datorie-capital-acoperire-dobanda", "rid": 623, "domain": "credit"}, {"slug": "efectul-de-levier-cum-folosesc-companiile-datoria", "rid": 745, "domain": "credit"}, {"slug": "levierul-financiar-datorie-capital-propriu-acoperire-dobanda", "rid": 847, "domain": "credit"}, {"slug": "datorie-senior-vs-subordonata-prioritate-rambursare", "rid": 632, "domain": "credit"}, {"slug": "datorie-senior-vs-subordonata", "rid": 752, "domain": "credit"}, {"slug": "datoria-senioara-vs-subordonata-prioritate-rambursare", "rid": 853, "domain": "credit"}, {"slug": "ciclul-creditului-faze-expansiune-varf-contractie-fund", "rid": 638, "domain": "credit"}, {"slug": "ciclul-creditului-faze-expansiune-varf-contractie-adancime", "rid": 760, "domain": "credit"}, {"slug": "ciclul-creditului-expansiune-varf-contractie-minim", "rid": 859, "domain": "credit"}, {"slug": "ce-este-creditul-imprumut-vs-creditare-instrumente-de-datori", "rid": 647, "domain": "credit"}, {"slug": "ce-este-creditul-imprumut-datorie-instrumente", "rid": 767, "domain": "credit"}, {"slug": "ce-este-creditul-imprumut-datorie-instrumente-2", "rid": 865, "domain": "credit"}, {"slug": "de-ce-creditul-anticipeaza-actiunile-puncte-cotitura", "rid": 654, "domain": "credit"}, {"slug": "de-ce-creditul-anticipeaza-actiunile-la-cotituri", "rid": 773, "domain": "credit"}]
const V_SCHEMA={type:'object',properties:{slug:{type:'string'},words:{type:'number'},lang_ok:{type:'boolean'},quiz_ok:{type:'boolean'},n_questions:{type:'number'},fixed:{type:'boolean'},corrections:{type:'array',items:{type:'string'}},notes:{type:'string'}},required:['slug','words','lang_ok','quiz_ok','n_questions','fixed']}
function vp(s){return `Esti redactor-sef la "Clubul Financiar" (Masterclass Bursa). Verifici si finalizezi o traducere + test deja publicate. Fisiere: ${SRC}/${s.slug}.html si ${QZ}/${s.slug}.json (sursa EN: rowid=${s.rid}, domeniu=${s.domain}).
Citeste ambele fisiere (Read). Compara cu sursa EN: sqlite3 ${DB} "SELECT body FROM textbook_chapters WHERE rowid=${s.rid};"
Verifica si CORECTEAZA in fisiere (Edit/Write):
1. TRADUCERE: romana impecabila, diacritice, FIDELA sensului EN, fara fraze stricate/anglicisme inutile/text netraducut/omisiuni. Doar fragment de corp (FARA <h1>/disclaimer/markdown/triple-backtick).
2. SEO preview: primele ~180 cuvinte (inainte de primul <h2>) contin cheia principala + termeni relevanti; ajusteaza intro daca lipsesc.
3. CELE 25 INTREBARI (in JSON): exact 25; fiecare RELEVANTA (ZERO umplutura — inlocuieste orice intrebare triviala/irelevanta); raspuns corect bine marcat (correct=indexul optiunii corecte, verifica matematic contra sursei); 4 optiuni plauzibile; explicatie corecta; mix ~60% concept / 40% fapt; variaza indexul corect (nu toate pe 0). Pastreaza JSON valid {"questions":[...]}.
Returneaza: slug="${s.slug}", words, lang_ok, quiz_ok, n_questions, fixed, corrections (lista scurta), notes.`}
log(`Re-verific ${SPECS.length} capitole Masterclass (verify-only).`)
const results = await parallel(SPECS.map(s => () => agent(vp(s), {label:`rv:${s.slug}`, phase:'Verify', schema:V_SCHEMA, agentType:'general-purpose', effort:'medium'}).then(v=>({slug:s.slug, verify:v||null}))))
const done=results.filter(Boolean)
log(`Re-verificare terminata: ${done.filter(d=>d.verify).length}/${SPECS.length}`)
return { done }
